config/routes.rb
RatchetRails::Application.routes.draw do
  root :to => 'home#show'
  match '/ratchet' => 'ratchet#show', :as => :ratchet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/ratchet_controller.rb
class RatchetController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/ratchet_helper.rb
module RatchetHelper

  # Accepts various types of title bar styles
  # :normal - full width and docked to the top of the viewport
  # :with_button - left or right aligned buttons (should be used for actions)
  #   * specify left, right or both as options[:position] for buttons
  # :with_directional_buttons - used for navigational purposes
  # :with_segmented_controller - house segmented controllers (w/ or w/o buttons)
  #   * specify both and either one, two or three segmented controllers w/ options[:amount]
  def title_bar(type, options = {})
    return if options[:visibility] == :hide
    title_bar_name  = t "#{controller_name}.title_bar.name"
    title_bar_left  = t "#{controller_name}.title_bar.left"
    title_bar_right = t "#{controller_name}.title_bar.right"
    class_left = 'button'
    class_right = 'button'
    case type
    when :normal
      type = content_tag :h1, title_bar_name, :class => 'title'
    when :with_buttons, :with_directional_buttons
      unless type == :with_buttons
        class_left  = 'button-prev'
        class_right = 'button-next'
      end
      if options[:position] == :left
        type = 
          (link_to title_bar_left, '#', :class => class_left) +
          (content_tag :h1, title_bar_name, :class => 'title')
      elsif options[:position] == :right
        type = 
          (content_tag :h1, (t 'name'), :class => 'title') +
          (link_to title_bar_right, '#', :class => class_right)
      elsif options[:position] == :both
        type =
          (link_to title_bar_left, '#', :class => class_left) +
          (content_tag :h1, title_bar_name, :class => 'title') +
          (link_to title_bar_right, '#', :class => class_right)
      else # Default to options[:right]
        type = 
          (content_tag :h1, title_bar_name, :class => 'title') +
          (link_to title_bar_right, '#', :class => class_right)
      end
    when :with_segmented_controller
      segmented_controller =
        if options[:amount] == :one
          content_tag :li, (link_to "One", '#'), :class => 'active'
        elsif options[:amount] == :two
          (content_tag :li, (link_to "One", '#'), :class => 'active') +
          (content_tag :li, (link_to "Two", '#'))
        elsif options[:amount] == :three
          (content_tag :li, (link_to "One", '#'), :class => 'active') +
          (content_tag :li, (link_to "Two", '#')) +
          (content_tag :li, (link_to "Three", '#'))
        else # Default to three segmented controllers
          (content_tag :li, (link_to "One", '#'), :class => 'active') +
          (content_tag :li, (link_to "Two", '#')) +
          (content_tag :li, (link_to "Three", '#'))
        end
      unless options[:amount].blank?
        type =
          (link_to title_bar_left, '#', :class => class_left) +
          (content_tag :ul, segmented_controller, :class => 'segmented-controller') +
          (link_to title_bar_right, '#', :class => class_right)
      else
        type =
          (content_tag :ul, segmented_controller, :class => 'segmented-controller')
      end
    end
    content_tag :header, type, :class => 'bar-title'
  end

  # Accepts :active and :hide option
  #   * Defaulted to display component
  def tab_bar_item(name, options = {})
    return if options[:visibility] == :hide
    css = (options[:active] == :active) ? 'tab-item active' : 'tab-item'
    entity =
      (content_tag :img, nil, :src => "assets/icon-#{name}.png", :class => 'tab-icon') +
      (content_tag :div, 'Label', :class => 'tab-label')
    item = link_to entity, ''
    content_tag :li, item, :class => css
  end

  # Accepts different count - :one, :two, :three
  # Accepts :hide option to remove component from view
  #   * Defaulted to display component
  def slider(count, options = {})
    return if options[:visibility] == :hide
    case count
    when :one
      image_1 = content_tag :img, nil, :src => "assets/slide-1.png"
      items =
        (content_tag :li, image_1)
    when :two
      image_1 = content_tag :img, nil, :src => "assets/slide-1.png"
      image_2 = content_tag :img, nil, :src => "assets/slide-2.png"
      items =
        (content_tag :li, image_1) +
        (content_tag :li, image_2)
    when :three
      image_1 = content_tag :img, nil, :src => "assets/slide-1.png"
      image_2 = content_tag :img, nil, :src => "assets/slide-2.png"
      image_3 = content_tag :img, nil, :src => "assets/slide-3.png"
      items =
        (content_tag :li, image_1) +
        (content_tag :li, image_2) +
        (content_tag :li, image_3)
    when :four
      image_1 = content_tag :img, nil, :src => "assets/slide-1.png"
      image_2 = content_tag :img, nil, :src => "assets/slide-2.png"
      image_3 = content_tag :img, nil, :src => "assets/slide-3.png"
      image_4 = content_tag :img, nil, :src => "assets/slide-4.png"
      items =
        (content_tag :li, image_1) +
        (content_tag :li, image_2) +
        (content_tag :li, image_3) +
        (content_tag :li, image_4)
    end
    list = content_tag :ul, items
    content_tag :div, list, :class => 'slider'
  end
end

app/views/home/show.html.haml
- title(t 'name')

%p= raw(t 'home.intro_1', :link => 'https://github.com/maker/ratchet')
%p= raw(t 'home.intro_2', :link_1 => 'http://haml.info', :link_2 => 'http://sass-lang.com')

= form_tag(ratchet_path) do
  #play= submit_tag(t 'home.ratchet_btn')

= form_tag("https://github.com/hopkinschris/ratchet-rails.git") do
  = submit_tag(t 'home.github_btn')

app/views/layouts/_footer.html.haml
%footer
  .copyright= raw(t 'footer.copyright')
  .footer-nav
    = link_to "Home", root_url
    \/
    = link_to "Mallow", "http://mallowapp.com"
    \/
    = link_to "Blog", "http://blog.chocol.it"
    \/
    = mail_to("chris@chocol.it", "Contact", :encode => "hex")

app/views/layouts/_head.html.haml
!!! 5
%head

  %title= yield(:title)
  %link{ :rel => 'author', :href => 'humans.txt' }

  - # Sets initial viewport load and disables zooming
  %meta{ :name => 'viewport', :content => 'initial-scale=1, maximum-scale=1, user-scalable=no' }

  - # Makes app "chrome-less" once bookmarked to home screen
  %meta{ :name => 'apple-mobile-web-app-capable', :content => 'yes' }
  %meta{ :name => 'apple-mobile-web-app-status-bar-style', :content => 'black' }

  - # Set Apple icons for when app is saved to home screen
  %link{ :rel => 'apple-touch-icon-precomposed', :sizes => '114x114', :href => 'assets/touch-icons/apple-touch-icon-114x114.png' }
  %link{ :rel => 'apple-touch-icon-precomposed', :sizes => '72x72', :href => 'assets/touch-icons/apple-touch-icon-72x72.png' }
  %link{ :rel => 'apple-touch-icon-precomposed', :sizes => '57x57', :href => 'assets/touch-icons/apple-touch-icon-57x57.png' }

  = favicon_link_tag 'favicon.png'

  = stylesheet_link_tag 'application', 'home', 'ratchet'

  - # Scope ratchet.js to it's own domain
  - if controller_name == 'ratchet'
    = javascript_include_tag 'ratchet.js'

  - # jQuery — Google Ajax API CDN Hosted
  = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'

  - # GAS — Google Analytics on Steroids (https://github.com/CardinalPath/gas)
  - if Rails.env.production?
    :javascript
      var _gas = _gas || [];
      _gas.push(['_setAccount', 'XX-XXXXXXXX-X']);
      _gas.push(['_setDomainName', 'domain.com']);
      _gas.push(['_trackPageview']);
      _gas.push(['_gasTrackForms']);
      _gas.push(['_gasTrackOutboundLinks']);
      _gas.push(['_gasTrackMaxScroll']);
      _gas.push(['_gasTrackMailto']);

      (function() {
      var ga = document.createElement('script');
      ga.type = 'text/javascript';
      ga.async = true;
      ga.src = '//cdnjs.cloudflare.com/ajax/libs/gas/1.10.1/gas.min.js';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(ga, s);
      })();

app/views/layouts/application.html.haml
= render 'layouts/head'

%body{ :class => controller_name, :id => action_name }

  %header
    %h1= t 'name'
    
  %section
    = yield

  = render 'layouts/footer'

= yield :javascripts

app/views/ratchet/_slider.html.haml
- # Component: Slider
= slider(:four, locals)

app/views/ratchet/_tab_bar.html.haml
- # Component: Tab bar
%nav.bar-tab{ :class => ('hide' if locals[:visibility] == :hide) }
  %ul.tab-inner
    = tab_bar_item(:home, { :visibility => :show, :active => :active })
    = tab_bar_item(:profile, { :visibility => :show })
    = tab_bar_item(:messages, { :visibility => :show })
    = tab_bar_item(:hamburger, { :visibility => :show })
    = tab_bar_item(:settings, { :visibility => :show })

app/views/ratchet/_title_bar.html.haml
- # Component: Title bar (see helper method for types)
= title_bar(:with_segmented_controller, { :amount => :three, :visibility => locals[:visibility] })

app/views/ratchet/show.html.haml
- title(t 'name')

= render 'title_bar', :locals => { :visibility => :show }

- # Scrollable HTML content
%div.content
  = render 'slider', :locals => { :visibility => :show }
  %div.content-padded

= render 'tab_bar', :locals => { :visibility => :show }